get:
  tags:
    - tasks
  summary: Задача
  parameters:
    - name: id
      in: path
      description: ID задачи
      required: true
      schema:
        type: integer
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            $ref: "../schemas/task.yaml"
  security:
    - KEY: [ ]
put:
  tags:
    - tasks
  summary: Изменить задачу
  parameters:
    - name: id
      in: path
      description: ID задачи
      required: true
      schema:
        type: integer
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../schemas/task.yaml"
    required: true
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            $ref: "../schemas/taskChangeResponse.yaml"
  security:
    - KEY: [ ]
delete:
  tags:
    - tasks
  summary: Удалить задачу
  parameters:
    - name: id
      in: path
      description: ID задачи
      required: true
      schema:
        type: integer
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: string
                example: Successfully deleted
  security:
    - KEY: [ ]