get:
  tags:
    - voip
  summary: Получить список путей
  parameters:
    - $ref: "#/components/parameters/desc"
    - $ref: "#/components/parameters/pageRows"
    - $ref: "#/components/parameters/pg"
    - $ref: "#/components/parameters/sort"
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../schemas/routes.yaml"
    400:
      description: Нет услуги Voip
      content:
        application/json:
          schema:
            type: object
            properties:
              errno:
                type: integer
                example: 30012
              errstr:
                type: string
                example: Not active voip service
  security:
    - USERSID: []