type: object
properties:
  abon:
    type: array
    items:
      $ref: '#/components/schemas/AbonUser'
  cams:
    type: array
    items:
      $ref: '#/components/schemas/CamsUser'
  internet:
    type: array
    items:
      $ref: '#/components/schemas/InternetUser'
  iptv:
    type: array
    items:
      $ref: '#/components/schemas/IptvUser'
  mobile:
    type: array
    items:
      $ref: '#/components/schemas/MobileUser'
  voip:
    type: array
    items:
      $ref: '#/components/schemas/VoipUser'