get:
  tags:
    - voip
  summary: Направления звонков
  parameters:
    - name: date
      in: query
      description: Дата добавления направления.
      schema:
        type: boolean
        default: true
    - name: descr
      in: query
      description: Описание направления.
      schema:
        type: boolean
        default: true
    - name: disable
      in: query
      description: Статус направления.
      schema:
        type: boolean
        default: true
    - name: id
      in: query
      description: ID направления.
      schema:
        type: boolean
        default: true
    - name: name
      in: query
      description: Название направления.
      schema:
        type: boolean
        default: true
    - name: parent
      in: query
      description: ID родительского пути куда привязан, зарезервировано и не используется.
      schema:
        type: boolean
        default: true
    - name: prefix
      in: query
      description: Префикс направления.
      schema:
        type: boolean
        default: true
    - $ref: "#/components/parameters/desc"
    - $ref: "#/components/parameters/pageRows"
    - $ref: "#/components/parameters/pg"
    - $ref: "#/components/parameters/sort"
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            $ref: "../schemas/routeInfoList.yaml"
  security:
    - KEY: []